### ISSUE TITLE
cmake fails on RHEL 7.6 ppc64le

### ISSUE THREAD

**Issue by drvadim** [IBM/data-broker#123] opened 2020-02-16 15:11 UTC
cmake now fails on RHEL 7.6 ppc64le

`cmake ../ -DWITH_DATA_ADAPTERS=1 -DCMAKE_INSTALL_PREFIX=/opt/databroker
Checking: /root/vadim/data-broker/backend/common
Checking: /root/vadim/data-broker/backend/fship
FOUND BE: fship
Checking: /root/vadim/data-broker/backend/network
Checking: /root/vadim/data-broker/backend/redis
FOUND BE: redis
Checking: /root/vadim/data-broker/backend/transports
LIBEVENT_PTHREADS_LIBRARIES=/usr/lib64/libevent_pthreads.so
Found libevent in: /usr/lib64/libevent_pthreads.so
CMake Error at backend/network/CMakeLists.txt:24 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "dbbe_network".

LIBEVENT_PTHREADS_LIBRARIES=/usr/lib64/libevent_pthreads.so
Found libevent in: /usr/lib64/libevent_pthreads.so
LIBEVENT_PTHREADS_LIBRARIES=/usr/lib64/libevent_pthreads.so
Found libevent in: /usr/lib64/libevent_pthreads.so
LIBEVENT_PTHREADS_LIBRARIES=/usr/lib64/libevent_pthreads.so
Found libevent in: /usr/lib64/libevent_pthreads.so
CMake Warning (dev) at utilities/perftests/CMakeLists.txt:37 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable MPI_ROOT is set to:

    /gpfs/apps/openmpi/4.0.1/gcc

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) 
-- Configuring incomplete, errors occurred!
`
`Currently Loaded Modules:
  1) Default   2) cmake/3.13.4   3) openmpi/4.0.1
`

**Comment by drvadim** [comment] 2020-02-16 15:20
I have tried with openmpi 3.0, which fixed MPI errors, but cmake still fails to produce a Makefile:

`$ module list

Currently Loaded Modules:
  1) Default   2) openmpi/3.0.0   3) cmake/3.13.4`


`$  cmake .. -DCMAKE_INSTALL_PREFIX=/opt/databroker -DWITH_DATA_ADAPTERS=1
Checking: /home/vadim/data-broker/backend/common
Checking: /home/vadim/data-broker/backend/fship
FOUND BE: fship
Checking: /home/vadim/data-broker/backend/network
Checking: /home/vadim/data-broker/backend/redis
FOUND BE: redis
Checking: /home/vadim/data-broker/backend/transports
LIBEVENT_PTHREADS_LIBRARIES=/usr/lib64/libevent_pthreads.so
Found libevent in: /usr/lib64/libevent_pthreads.so
CMake Error at backend/network/CMakeLists.txt:24 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "dbbe_network".


LIBEVENT_PTHREADS_LIBRARIES=/usr/lib64/libevent_pthreads.so
Found libevent in: /usr/lib64/libevent_pthreads.so
LIBEVENT_PTHREADS_LIBRARIES=/usr/lib64/libevent_pthreads.so
Found libevent in: /usr/lib64/libevent_pthreads.so
LIBEVENT_PTHREADS_LIBRARIES=/usr/lib64/libevent_pthreads.so
Found libevent in: /usr/lib64/libevent_pthreads.so
CMake Warning (dev) at utilities/perftests/CMakeLists.txt:37 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable MPI_ROOT is set to:

    /gpfs/apps/openmpi/3.0.0/gcc

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

Found MPI lib at: /gpfs/apps/openmpi/3.0.0/gcc/include
-- Configuring incomplete, errors occurred!
See also "/home/vadim/data-broker/build/CMakeFiles/CMakeOutput.log".
`

**Comment by lasch** [comment] 2020-02-18 01:30
This error indicates a problem with the cmake version and interface libraries.
So far I can't reproduce the problem on RHEL 7.6 ppc64le. I'll continue investigating.

**Comment by lasch** [comment] 2020-02-19 14:29
fixed with commit e30aac5

**Closed as completed by lasch** 2020-02-19 14:29 UTC
